polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

triptech_web/urls.py
from django.urls import path
from . import views

app_name = 'triptech_web'
urlpatterns = [
    # ex: /triptech_web/
    path('', views.FileView.as_view(), name='files'),
    # ex: /triptech_web/5
    path('<int:pk>/', views.data, name='data'),
    # ex: /assignments/
    path('assignments/', views.AssignmentView.as_view(), name='assignments'),
    # ex: /assignments/new
    path('assignments/new/', views.new_assignment, name='new_assignment'),
    # ex: /assignments/5
    path('assignments/<int:pk>', views.assignment_details, name='view_assignment'),
    # ex: /assignments/5/edit
    path('assignments/<int:pk>/edit', views.edit_assignment, name='edit_assignment'),
    # ex: /assignment/5/submissions/
    path('assignments/<int:pk>/submissions/', views.SubmissionView.as_view(), name='submissions'),
    # es: /assignment/5/submissions/new
    path('assignments/<int:pk>/submissions/new', views.submission_new, name='submissions_new'),
    # ex: /assignment/5/submissions/1
    path('assignments/<int:pk>/submissions/<int:pk_sub>', views.submission_details, name='submissions_view'),
    # ex: /assignments/5/submissions/1/edit
    path('assignments/<int:pk>/submissions/<int:pk_sub>/edit', views.submission_edit, name='submissions_edit')
]

triptech_web_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('', include('triptech_web.urls'))
]

triptech_web/models.py
from django.db import models


# Create your models here.
class Filenames(models.Model):
    filename = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date')

    def __str__(self):
        return self.filename


class Data(models.Model):
    filename = models.ForeignKey(Filenames, on_delete=models.CASCADE)
    voltage = models.FloatField()
    current = models.FloatField()

    def __str__(self):
        return "Voltage: {0}, Current: {1}".format(self.voltage, self.current)


class Assignments(models.Model):
    def __str__(self):
        return self.title

    title = models.CharField(max_length=200)
    date_created = models.DateTimeField('date')
    text = models.CharField(max_length=256)
    metadata1 = models.CharField(max_length=256)
    metadata2 = models.CharField(max_length=256)


class Submissions(models.Model):
    def __str__(self):
        return self.student_name

    student_name = models.CharField(max_length=200)
    assignment = models.ForeignKey(Assignments, on_delete=models.CASCADE)
    date = models.DateTimeField('date')
    data_location = models.CharField(max_length=256)
    metadata1 = models.CharField(max_length=256)
    metadata2 = models.CharField(max_length=256)

triptech_web/forms.py
from django import forms


# Create your forms here.
class NewAssignmentForm(forms.Form):
    assignment_name = forms.CharField(label='Assignment name', max_length=100)
    assignment_description = forms.CharField(label='Assignment Description', widget=forms.Textarea)


class NewSubmissionForm(forms.Form):
    student_name = forms.CharField(label='Student name', max_length=100)
    data_location = forms.CharField(label='Data location', max_length=260)

triptech_web/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, render_to_response
from django.utils import timezone
from django.urls import reverse
from django.views import generic

from .models import Filenames, Data, Assignments, Submissions
from .forms import NewAssignmentForm, NewSubmissionForm

from bokeh.io import output_file, show
from bokeh.layouts import widgetbox
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import Select
from bokeh.plotting import figure, output_file, show
from bokeh.embed import components, file_html


# Create your views here.
class FileView(generic.ListView):
    template_name = 'triptech_web/files.html'
    context_object_name = 'filename_list'

    def get_queryset(self):
        """
        Returns the files currently in the system
        """
        return Filenames.objects.all()


class AssignmentView(generic.ListView):
    template_name = 'triptech_web/assignment_list.html'
    context_object_name = 'assignment_list'

    def get_queryset(self):
        """
        Returns the assignments currently available from the database
        :return:
        """
        return Assignments.objects.all()


class SubmissionView(generic.ListView):
    template_name = 'triptech_web/submission_list.html'
    context_object_name = 'submission_list'

    def get_queryset(self):
        """
        Returns the submissions currently available from the database
        :return:
        """
        pk = self.kwargs['pk']
        return Submissions.objects.filter(assignment_id=pk)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pk'] = self.kwargs['pk']
        context['assignment'] = Assignments.objects.filter(pk=self.kwargs['pk'])[0].title
        return context


def assignment_details(request, pk):

    if request.method == 'POST':
        a = Assignments.objects.get(pk=pk)
        a.delete()
        return HttpResponseRedirect(reverse('triptech_web:assignments'))

    assignment = Assignments.objects.get(pk=pk)

    context = {
        'title': assignment.title,
        'date_created': assignment.date_created,
        'text': assignment.text,
        'pk': pk
    }

    return render(request, 'triptech_web/assignment_view.html', context)


def new_assignment(request):

    if request.method == 'POST':
        form = NewAssignmentForm(request.POST)
        if form.is_valid():
            a = Assignments(title=form.cleaned_data['assignment_name'], date_created=timezone.now(),
                            text=form.cleaned_data['assignment_description'], metadata1='', metadata2='')
            a.save()
            return HttpResponseRedirect(reverse('triptech_web:assignments'))
    else:
        form = NewAssignmentForm()

    return render(request, 'triptech_web/assignment_new.html', {'form': form})


def edit_assignment(request, pk):

    if request.method == 'POST':
        form = NewAssignmentForm(request.POST)
        if form.is_valid():
            a = Assignments.objects.get(pk=pk)
            a.title = form.cleaned_data['assignment_name']
            a.text = form.cleaned_data['assignment_description']
            a.save()
            return HttpResponseRedirect(reverse('triptech_web:view_assignment', kwargs={'pk': pk}))
    else:
        assignment = Assignments.objects.get(pk=pk)
        form = NewAssignmentForm({'assignment_name': assignment.title, 'assignment_description': assignment.text})

    return render(request, 'triptech_web/assignment_edit.html', {'form': form, 'pk': pk})


def submission_details(request, pk, pk_sub):
    submission = Submissions.objects.get(pk=pk_sub)

    context = {
        'student_name': submission.student_name,
        'date': submission.date,
        'assignment': Assignments.objects.filter(pk=pk)[0].title,
        'data_location': submission.data_location,
        'pk': pk,
        'pk_sub': pk_sub
    }

    return render(request, 'triptech_web/submission_view.html', context)


def submission_new(request, pk):
    if request.method == 'POST':
        form = NewSubmissionForm(request.POST)
        if form.is_valid():
            s = Submissions(student_name=form.cleaned_data['student_name'], date=timezone.now(),
                            data_location=form.cleaned_data['data_location'],
                            metadata1='', metadata2='', assignment_id=pk)
            s.save()
            return HttpResponseRedirect(reverse('triptech_web:submissions', kwargs={'pk': pk}))
    else:
        form = NewSubmissionForm()

    return render(request, 'triptech_web/submission_new.html', {'form': form, 'pk': pk})


def submission_edit(request, pk, pk_sub):
    if request.method == 'POST':
        form = NewSubmissionForm(request.POST)
        if form.is_valid():
            s = Submissions.objects.get(pk=pk_sub)
            s.student_name = form.cleaned_data['student_name']
            s.data_location = form.cleaned_data['data_location']
            s.save()
            return HttpResponseRedirect(reverse('triptech_web:submissions_view', kwargs={'pk': pk, 'pk_sub': pk_sub}))
    else:
        sub = Submissions.objects.get(pk=pk_sub)
        form = NewSubmissionForm({'student_name': sub.student_name, 'data_location': sub.data_location})

    return render(request, 'triptech_web/submission_edit.html', {'form': form, 'pk': pk, 'pk_sub': pk_sub})


def data(request, pk, **kwargs):

    plot_type = None

    for name, value in kwargs.items():
        if name == 'plot_type':
            plot_type = value

    if plot_type == None:
        plot_type = 'line'

    x = []
    y = []

    file = Filenames.objects.get(pk=pk)

    for datapoint in file.data_set.all():
        x.append(datapoint.voltage)
        y.append(datapoint.current)

    title = file.filename
    plot = figure(title=title,
                  x_axis_label='Voltage [V]',
                  y_axis_label='Current [A]',
                  plot_width=650,
                  plot_height=650,)

    if len(x) <= 1:
        plot_type = 'scatter'

    if plot_type == 'line':
        plot.line(x, y, line_width=2)
    elif plot_type == 'scatter':
        plot.scatter(x, y, line_width=2)
    elif plot_type == 'hbar':
        plot.hbar(x, y)
    elif plot_type == 'vbar':
        plot.vbar(x, y)

    script, div = components(plot)

    type = Select(title='Plot Type:', value='line', options=['scatter', 'hbar', 'vbar'])

    controls = [type]
    """
    for control in controls:
        control.on_change('value', lambda attr, old, new: update())
    """
    source = ColumnDataSource(data=dict(x=[], y=[], color=[], voltage=[], current=[]))
    TOOLTIPS=[
        ('Voltage', '@voltage'),
        ('Current', '@current')
    ]

    type_script, type_div = components(widgetbox(type))

    context = {
        'filenames': file,
        'script': script,
        'div': div,
        'type_script': type_script,
        'type_div': type_div
    }

    return render_to_response('triptech_web/data.html', context)

triptech_web/templates/triptech_web/assignment_edit.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% include "triptech_web/generic_head.html" %}
</head>
<body class="triptech-body">
    {% include "triptech_web/menu.html" %}

    <div id="triptech-content" class="triptech-content">
        <h1>New Assignment:</h1>

        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <div style="padding-bottom:10px;">
            <form method="post">
                {% csrf_token %}
                <div>{{ form.assignment_name.label }}</div>
                <div>{{ form.assignment_name }}</div>
                <div>{{ form.assignment_description.label }}</div>
                <div>{{ form.assignment_description }}</div>
                <input type="submit" value="Update" />
            </form>
        </div>
        <div><a href="{% url "triptech_web:view_assignment" pk %}" class="btn btn-info" role="button">Back</a></div>
    </div>

</body>
</html>

triptech_web/templates/triptech_web/assignment_list.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% include "triptech_web/generic_head.html" %}
</head>
<body class="triptech-body">
    {% include "triptech_web/menu.html" %}

    <div id="triptech-content" class="triptech-content">
        <div style="padding-bottom:10px;"><a href="{% url "triptech_web:new_assignment" %}" class="btn btn-info" role="button">New</a></div>
        {% if assignment_list %}
            <div class="list-group">
                {% for assignment in assignment_list %}
                    <a href="{% url 'triptech_web:view_assignment' assignment.id %}" class="list-group-item list-group-item-action triptech-list">
                        {{ assignment.title}}
                    </a>
                {% endfor %}
            </div>
        {% else %}
            <p>No assignments are available.</p>
        {% endif %}
    </div>
</body>
</html>

triptech_web/templates/triptech_web/assignment_new.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% include "triptech_web/generic_head.html" %}
</head>
<body class="triptech-body">
    {% include "triptech_web/menu.html" %}

    <div id="triptech-content" class="triptech-content">
        <h1>New Assignment:</h1>

        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <div style="padding-bottom:10px;">
            <form method="post">
                {% csrf_token %}
                <div>{{ form.assignment_name.label }}</div>
                <div>{{ form.assignment_name }}</div>
                <div>{{ form.assignment_description.label }}</div>
                <div>{{ form.assignment_description }}</div>
                <input type="submit" value="Create" />
            </form>
        </div>
        <div><a href="{% url "triptech_web:assignments" %}" class="btn btn-info" role="button">Back</a></div>
    </div>

</body>
</html>

triptech_web/templates/triptech_web/assignment_view.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% include "triptech_web/generic_head.html" %}
</head>
<body class="triptech-body">
    {% include "triptech_web/menu.html" %}

    <div id="triptech-content" class="triptech-content">
        <h1>Assignment details:</h1>
        <div class="alert alert-warning alert-dismissible fade show" style="display: none;" id="delete-warning">
            <button type="button" class="close" onclick="cancelDelete()">&times;</button>
            <strong>Warning!</strong> This will delete assignment and submissions. Click on "x" to cancel.
            <form method="post">
                {% csrf_token %}
                <input type="submit" value="Delete" />
            </form>
        </div>
        <p>{{ title }}</p>
        <p>{{ date_created }}</p>
        <p>{{ text }}</p>
        <div>
            <a href="{% url "triptech_web:submissions" pk %}" class="btn btn-info" role="button">View Submissions</a>
            <a href="{% url "triptech_web:edit_assignment" pk %}" class="btn btn-info" role="button">Edit</a>
            <a href="javascript:void(0)" class="btn btn-info" onclick="deleteConfirm()">Delete</a>
            <a href="{% url "triptech_web:assignments" %}" class="btn btn-info" role="button">Back</a>
        </div>
    </div>
</body>
<script type="text/javascript">
    /* Pops up confirmation, then if clicked again will delete */
    function cancelDelete() {
        var x = document.getElementById("delete-warning");
        x.style.display = "none";
    }
    function deleteConfirm() {
        var x = document.getElementById("delete-warning");
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.con;
        }

    }
</script>
</html>

triptech_web/templates/triptech_web/data.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% include "triptech_web/generic_head.html" %}
    <link
        href="https://cdn.pydata.org/bokeh/release/bokeh-0.12.16.min.css"
        rel="stylesheet" type="text/css">
    <link
        href="https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.16.min.css"
        rel="stylesheet" type="text/css">
    <link
        href="https://cdn.pydata.org/bokeh/release/bokeh-tables-0.12.16.min.css"
        rel="stylesheet" type="text/css">

    <script src="https://cdn.pydata.org/bokeh/release/bokeh-0.12.16.min.js"></script>
    <script src="https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.16.min.js"></script>
    <script src="https://cdn.pydata.org/bokeh/release/bokeh-tables-0.12.16.min.js"></script>
    {{ script | safe }}
    {{ type_script | safe }}
</head>

<body class="triptech-body">
    {% include "triptech_web/menu.html" %}
    <div id="triptech-content" class="triptech-content">
        <div class="container-fluid">
            <div class="row" style="padding-bottom: 10px;">
                <div class="col-med-3 col-sm-3 col-xs-3"> <h1>{{ filenames.filename }}</h1> </div>
                <div class="col-med-9 col-sm-9 col-xs-9"> <a href="{% url "triptech_web:files" %}" class="btn btn-info" role="button">Go back</a> </div>
            </div>

            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

            <!--<form action="{% url 'triptech_web:data' filenames.id %}" method="post">-->
            {% csrf_token %}
            <div class="row">
            <div class="col-med-3 col-sm-3 col-xs-3">
                <table class="table table-striped table-responsive">
                    <thead>
                        <tr>
                            <th>Voltage</th>
                            <th>Current</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for data in filenames.data_set.all %}
                            <tr>
                                <td>{{ data.voltage }}</td>
                                <td>{{ data.current }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-med-9 col-sm-9 col-xs-9">{{ div | safe }}</div>
            <div class="row" style="padding-left: 15px;">
                {{ type_div | safe }}
            </div>
        </div>
        <!--</form>-->
        </div>
    </div>

</html>

triptech_web/templates/triptech_web/files.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% include "triptech_web/generic_head.html" %}
</head>
<body class="triptech-body">
    {% include "triptech_web/menu.html" %}

    <div id="triptech-content" class="triptech-content">
        {% if filename_list %}
            <div class="list-group">
                {% for file in filename_list %}
                    <a href="{% url 'triptech_web:data' file.id %}" class="list-group-item list-group-item-action triptech-list">
                        {{ file.filename}}
                    </a>
                {% endfor %}
            </div>
        {% else %}
            <p>No files are available.</p>
        {% endif %}
    </div>
</body>
</html>

triptech_web/templates/triptech_web/generic_head.html
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'triptech_web/menu.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'triptech_web/style.css' %}" />

    <!-- Add icon library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>

triptech_web/templates/triptech_web/menu.html
{% load static %}
<script type="text/javascript">
    /* Set the width of the side navigation to 250px and the left margin of the page content to 250px */
    function openNav() {
        document.getElementById("triptech-sidenav").style.width = "250px";
        document.getElementById("triptech-content").style.marginLeft = "260px";
        document.getElementById("triptech-content").style.width = "calc(100% - 270px)";
    }

    /* Set the width of the side navigation to 0 and the left margin of the page content to 0 */
    function closeNav() {
        document.getElementById("triptech-sidenav").style.width = "0";
        document.getElementById("triptech-content").style.marginLeft = "10px";
        document.getElementById("triptech-content").style.width = "calc(100% - 20px)";
    }
</script>
<div class="triptech-container top">
    <img src="{% static "triptech_web/images/main-logo-small-2.png" %}" onclick="openNav()">
</div>

<div id="triptech-sidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    <a href="{% url 'triptech_web:files' %}">Files</a>
    <a href="{% url 'triptech_web:assignments' %}">Assignments</a>
</div>

triptech_web/templates/triptech_web/submission_edit.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% include "triptech_web/generic_head.html" %}
</head>
<body class="triptech-body">
    {% include "triptech_web/menu.html" %}

    <div id="triptech-content" class="triptech-content">
        <h1>New Submission:</h1>

        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <div style="padding-bottom:10px;">
            <form method="post">
                {% csrf_token %}
                <div>{{ form.student_name.label }}</div>
                <div>{{ form.student_name }}</div>
                <div>{{ form.data_location.label }}</div>
                <div>{{ form.data_location }}</div>
                <input type="submit" value="Update" />
            </form>
        </div>
        <div><a href="{% url "triptech_web:submissions_view" pk pk_sub %}" class="btn btn-info" role="button">Back</a></div>
    </div>

</body>
</html>

triptech_web/templates/triptech_web/submission_list.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% include "triptech_web/generic_head.html" %}
</head>
<body class="triptech-body">
    {% include "triptech_web/menu.html" %}

    <div id="triptech-content" class="triptech-content">
    <div style="padding-bottom:10px;">
        <h1>Submissions for {{ submission_list.first.assignment }}</h1>
        <a href="{% url "triptech_web:submissions_new" pk %}" class="btn btn-info" role="button">New</a>
        <a href="{% url "triptech_web:view_assignment" pk%}" class="btn btn-info" role="button">Back</a>
    </div>
        {% if submission_list %}
            <div class="list-group">
                {% for submission in submission_list %}
                    <a href="{% url 'triptech_web:submissions_view' submission.assignment_id submission.id %}" class="list-group-item list-group-item-action triptech-list">
                        {{ submission.student_name }}
                    </a>
                {% endfor %}
            </div>
        {% else %}
            <p>No submissions are available.</p>
        {% endif %}
    </div>
</body>
</html>

triptech_web/templates/triptech_web/submission_new.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% include "triptech_web/generic_head.html" %}
</head>
<body class="triptech-body">
    {% include "triptech_web/menu.html" %}

    <div id="triptech-content" class="triptech-content">
        <h1>New Submission:</h1>

        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <div style="padding-bottom:10px;">
            <form method="post">
                {% csrf_token %}
                <div>{{ form.student_name.label }}</div>
                <div>{{ form.student_name }}</div>
                <div>{{ form.data_location.label }}</div>
                <div>{{ form.data_location }}</div>
                <input type="submit" value="Create" />
            </form>
        </div>
        <div><a href="{% url "triptech_web:submissions" pk %}" class="btn btn-info" role="button">Back</a></div>
    </div>

</body>
</html>

triptech_web/templates/triptech_web/submission_view.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% include "triptech_web/generic_head.html" %}
</head>
<body class="triptech-body">
    {% include "triptech_web/menu.html" %}
    <div id="triptech-content" class="triptech-content">
        <h1>Assignment details:</h1>
        <p>{{ student_name }}</p>
        <p>{{ date }}</p>
        <p>{{ data_location }}</p>
        <div>
            <a href="{% url "triptech_web:submissions_edit" pk pk_sub %}" class="btn btn-info" role="button">Edit</a>
            <a href="{% url "triptech_web:submissions" pk %}" class="btn btn-info" role="button">Back</a>
        </div>
    </div>
</body>
</html>